services:
    eztags.pagerfanta.related_content_adapter:
        class: Netgen\TagsBundle\Core\Pagination\Pagerfanta\RelatedContentAdapter
        arguments:
            - "@eztags.api.service.tags"
            - "@ezpublish.config.resolver"

    eztags.pagerfanta.children_tags_adapter:
        class: Netgen\TagsBundle\Core\Pagination\Pagerfanta\ChildrenTagsAdapter
        arguments:
            - "@eztags.api.service.tags"
            -
    eztags.pagerfanta.search_tags_adapter:
        class: Netgen\TagsBundle\Core\Pagination\Pagerfanta\SearchTagsAdapter
        arguments:
            - "@eztags.api.service.tags"

    eztags.pagerfanta.view.eztags_admin:
        class: Netgen\TagsBundle\Core\Pagination\Pagerfanta\View\TagsAdminView
        # Not being lazy results in out of memory exceptions on eZ Platform 2.0,
        # probably due to @twig dependency
        lazy: true
        arguments:
            - "@twig"
            - "%eztags.admin.default_pager_template%"
        tags:
            - { name: pagerfanta.view, alias: eztags_admin }
