name: Tests

on:
  push:
    branches:
      - 'master'
      - '[0-9].[0-9]+-release'
  pull_request: ~

jobs:
  tests:
    name: ${{ matrix.php }} / ${{ matrix.phpunit }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['7.3', '7.4']
        phpunit: ['phpunit.xml', 'phpunit-integration-legacy.xml']

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - run: composer --version
      - run: composer validate --strict

      # Install Flex as a global dependency to enable usage of extra.symfony.require
      # while keeping Flex recipes from applying
      - run: composer global require --no-scripts symfony/flex

      - run: composer update --prefer-dist

      - run: vendor/bin/phpunit -c ${{ matrix.phpunit }} --colors=always --coverage-clover=coverage.xml
